manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: m165437
      url-base: https://github.com/M165437         # gem
    - name: gpeye
      url-base: https://github.com/GPeye           # slideshow
    - name: mctechnology17
      url-base: https://github.com/mctechnology17  # gem with dog
    - name: dsifry
      url-base: https://github.com/dsifry          # bongo cat
    - name: gpeye
      url-base: https://github.com/GPeye           # mario
    - name: whoop-t
      url-base: https://github.com/whoop-t         # one punch
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.2
      import: app/west.yml
    - name: nice-view-gem
      remote: m165437
      revision: main
    - name: hammerbeam-slideshow
      remote: gpeye
      revision: main
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main  
    - name: nice-view-mod
      remote: dsifry
      revision: main
    - name: mario-peripheral-animation
      remote: gpeye
      revision: main
    - name: nice-one-punch-ok
      remote: whoop-t
      revision: main
  self:
    path: config
